title: Maxime ANDRÉ
logo: "/images/logo.jpg"
description: >
  <br><br>
  Ingénieur Micro-électronique
  <br><br>
  <a href="https://www.linkedin.com/in/maxime-andré-0b24a4a5/">LinkedIn</a>

theme: jekyll-theme-minimal
