title: Quentin ANDRÉ
logo: "/images/logo.jpg"
description: >
<style type="text/css">
p {
  font-family:Arial;
}
a:hover {
  font-weight:normal;
  color: #0000ff;
}
</style>
  <br><br>
  Étudiant en Master 2 Informatique à l'université de Montpellier
  <br><br>
  Actuellement à la recherche d'un stage de fin de formation dans le domaine du jeux vidéo ou de l'imagerie 3D
  <br><br>
  <a href="https://www.linkedin.com/in/quentin-andré-9791b0111/">LinkedIn</a>

theme: jekyll-theme-minimal
