title: Maxime ANDRÉ
logo: "/images/logo.jpg"
description: >
  <br><br>
  Ingénieur Spécialité Systèmes Électrique
  <br><br>
  Electronique de puissance<br>
  Electrotechnique<br>
  Electronique de signal<br>
  Informatique Embarqué<br>
  Traitement du signal<br>
  Modélisation 3D<br>
  Optique<br>
  <a href="https://www.linkedin.com/in/maxime-andré-0b24a4a5/">LinkedIn</a>

theme: jekyll-theme-minimal
